# Generated by Django 3.1.5 on 2021-02-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('Last_name', models.CharField(max_length=64)),
                ('image', models.URLField(blank=True)),
                ('about_me', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.BooleanField()),
                ('css', models.BooleanField()),
                ('js', models.BooleanField()),
                ('react', models.BooleanField()),
                ('nodejs', models.BooleanField()),
                ('express', models.BooleanField()),
                ('django', models.BooleanField()),
                ('heroku', models.BooleanField()),
                ('vercel', models.BooleanField()),
                ('githab_pages', models.BooleanField()),
                ('python', models.BooleanField()),
                ('postgresql', models.BooleanField()),
                ('mongodb', models.BooleanField()),
                ('git', models.BooleanField()),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=63)),
                ('live_url', models.URLField()),
                ('github_url', models.URLField()),
                ('description', models.TextField()),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.projects')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='projects',
            field=models.ManyToManyField(through='Blog.Ownership', to='Blog.Projects'),
        ),
        migrations.AddField(
            model_name='blog',
            name='skils',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.skils'),
        ),
        migrations.AddField(
            model_name='blog',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
